#!/usr/bin/env node
// scrub — remove Claude attribution from a GitHub issue, PR, comment or review body (O09, K006).
//
//   node .harness/tools/scrub.mjs            in Actions (harness-scrub.yml): reads the event, re-reads
//                                            the body it names, and saves it back only if scrubbing changed it
//   node .harness/tools/scrub.mjs --stdin    prints the scrubbed text of stdin (tests, local use)
//
// What goes: a line saying "Generated by/with Claude Code", a Co-authored-by or Claude-Session line
// naming Claude, and every claude.ai link (a Markdown link loses its text too); a line left with no
// words, and a `---` rule left dangling at the end, go with them. Fenced code blocks are left alone,
// so a body can still quote these strings on purpose. Everything else is byte-for-byte unchanged.
//
// Safe on untrusted input: the body is only data to a few linear regexes, no code is checked out
// from the event, and the edit is made with GITHUB_TOKEN, whose events start no workflow (no loop).

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const GENERATED = /generated\s+(by|with)\s+\[?claude[\s_-]*code/i;
const TRAILER = /^\s*(co-authored-by:[^\n]*\bclaude\b|claude-session:)/i;
const MD_LINK = /\[[^\]\n]*\]\(\s*<?https?:\/\/(?:[a-z0-9-]+\.)*claude\.ai(?![\w-]|\.\w)(?:[/?#][^)\s]*)?>?\s*\)/gi;
const BARE_URL = /<?https?:\/\/(?:[a-z0-9-]+\.)*claude\.ai(?![\w-]|\.\w)(?:[/?#][^\s)>\]]*)?>?/gi;

/** The text without Claude attribution. Returns the input unchanged when there is none. */
export function scrub(text) {
  if (typeof text !== 'string' || !text) return text;
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const out = [];
  let fence = null, removed = false;
  for (const line of text.split(/\r?\n/)) {
    const f = line.match(/^\s*(`{3,}|~{3,})/);
    if (fence) { out.push(line); if (f && f[1][0] === fence[0] && f[1].length >= fence.length) fence = null; continue; }
    if (f) { fence = f[1]; out.push(line); continue; }
    if (GENERATED.test(line) || TRAILER.test(line)) { removed = true; continue; }
    let l = line.replace(MD_LINK, '').replace(BARE_URL, '');
    if (l !== line) {
      removed = true;
      // a separator the link leaves dangling: "by X · _" → "by X_"
      l = l.replace(/\s*[·|•,:–—-]\s*(?=[_*]*\s*$)/, '').replace(/\(\s*\)/g, '').replace(/(\S)[ \t]{2,}(?=\S)/g, '$1 ').replace(/[ \t]+$/, '');
      if (!/[\p{L}\p{N}]/u.test(l)) continue;
    }
    out.push(l);
  }
  if (!removed) return text;
  while (out.length && out.at(-1).trim() === '') out.pop();
  if (out.length && /^\s*(-{3,}|\*{3,}|_{3,})\s*$/.test(out.at(-1))) { out.pop(); while (out.length && out.at(-1).trim() === '') out.pop(); }
  return out.join(eol).replace(/(\r?\n){3,}/g, `${eol}${eol}`) + (/\r?\n$/.test(text) && out.length ? eol : '');
}

// --- GitHub Actions entry point -------------------------------------------------------------------------
/** The REST path of the body an event names, and how to save it. */
export function target(name, p) {
  const repo = p.repository?.full_name;
  if (!repo) return null;
  if (name === 'issues' && p.issue) return { path: `/repos/${repo}/issues/${p.issue.number}`, method: 'PATCH' };
  if ((name === 'pull_request_target' || name === 'pull_request') && p.pull_request) return { path: `/repos/${repo}/pulls/${p.pull_request.number}`, method: 'PATCH' };
  if (name === 'issue_comment' && p.comment) return { path: `/repos/${repo}/issues/comments/${p.comment.id}`, method: 'PATCH' };
  if (name === 'pull_request_review_comment' && p.comment) return { path: `/repos/${repo}/pulls/comments/${p.comment.id}`, method: 'PATCH' };
  if (name === 'pull_request_review' && p.review && p.pull_request) return { path: `/repos/${repo}/pulls/${p.pull_request.number}/reviews/${p.review.id}`, method: 'PUT' };
  return null;
}

async function api(method, path, body) {
  const r = await fetch(`${process.env.GITHUB_API_URL || 'https://api.github.com'}${path}`, {
    method,
    headers: {
      accept: 'application/vnd.github+json', 'x-github-api-version': '2022-11-28', 'user-agent': 'harness-kit-scrub',
      authorization: `Bearer ${process.env.GITHUB_TOKEN}`, ...(body ? { 'content-type': 'application/json' } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await r.text();
  if (!r.ok) throw new Error(`${method} ${path} answered ${r.status}: ${text.slice(0, 200)}`);
  return JSON.parse(text);
}

async function main() {
  if (process.argv.includes('--stdin')) { process.stdout.write(scrub(readFileSync(0, 'utf8'))); return; }
  const name = process.env.GITHUB_EVENT_NAME;
  const t = target(name, JSON.parse(readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8')));
  if (!t) { console.log(`scrub: nothing to scrub on ${name}`); return; }
  if (!process.env.GITHUB_TOKEN) throw new Error('GITHUB_TOKEN is not set');
  // re-read: the event's copy may be older than a later edit, which must not be overwritten
  const now = await api('GET', t.path);
  const clean = scrub(now.body);
  if (clean === now.body) { console.log(`scrub: ${t.path}: no attribution`); return; }
  await api(t.method, t.path, { body: clean });
  console.log(`scrub: ${t.path}: attribution removed`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((e) => { console.error(`scrub: ${e.message}`); process.exit(1); });
}
