#!/usr/bin/env node
// test-scrub — the attribution scrubber removes what O09 forbids and nothing else (K006).
//
//   node tools/test-scrub.mjs        exit 0 = every case held

import { scrub, target } from '../.harness/tools/scrub.mjs';

let n = 0;
const eq = (got, want, what) => {
  n++;
  if (got !== want) { console.log(`test-scrub: FAIL ${n}. ${what}\n--- got ---\n${got}\n--- want ---\n${want}`); process.exit(1); }
  console.log(`test-scrub: ok ${n}. ${what}`);
};

// catches: the footers and links the platform and sessions add
eq(scrub('Fixes the build.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n'), 'Fixes the build.\n', 'a "Generated by" footer and its rule go');
eq(scrub('Summary.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_01ABC\n'), 'Summary.\n', '"Generated with" line and a bare session link go');
eq(scrub('_Requested by **Jahjah** · [project thread](https://claude.ai/code/project/chan_1?thread=cmsg_2)_\n\nBody.'), '_Requested by **Jahjah**_\n\nBody.', 'a thread link goes with its dangling separator; the rest of the line stays');
eq(scrub('Done.\n\nCo-Authored-By: Claude Opus <noreply@anthropic.com>\nClaude-Session: https://claude.ai/code/session_1\n'), 'Done.\n', 'co-author and session lines go');
eq(scrub('See https://claude.ai/code/session_1 for the run.'), 'See for the run.', 'an inline link goes, the sentence stays');
eq(scrub('Done.\r\n\r\n---\r\n_Generated by [Claude Code](https://claude.ai/code)_\r\n'), 'Done.\r\n', 'CRLF bodies keep CRLF');
eq(scrub('a\n\n<https://www.claude.ai/x>\n\nb'), 'a\n\nb', 'an autolink and the blank lines around it collapse');

// accepts: correct text is returned unchanged, byte for byte
const keep = [
  'Plain body.\n\n---\n\nA section after a rule.\n',
  'Uses the Anthropic API via claude-sonnet; docs at https://docs.anthropic.com/claude.\n',
  'Written with care by Claude the colleague, not a footer.',
  '```text\nGenerated by Claude Code\nhttps://claude.ai/code/x\n```\n',
  'notclaude.ai.example.com and https://example.com/claude.ai stay',
  'https://claude.ai.example.com/x and https://notclaude.ai/y are other hosts',
  '',
];
for (const k of keep) eq(scrub(k), k, `unchanged: ${JSON.stringify(k.slice(0, 40))}`);
eq(scrub(null), null, 'a null body stays null');

// the event → endpoint map
const repo = { full_name: 'o/r' };
eq(target('issues', { repository: repo, issue: { number: 3 } })?.path, '/repos/o/r/issues/3', 'issue body');
eq(target('pull_request_target', { repository: repo, pull_request: { number: 4 } })?.path, '/repos/o/r/pulls/4', 'PR body');
eq(target('issue_comment', { repository: repo, issue: { number: 4 }, comment: { id: 9 } })?.path, '/repos/o/r/issues/comments/9', 'issue or PR comment');
eq(target('pull_request_review_comment', { repository: repo, comment: { id: 8 } })?.path, '/repos/o/r/pulls/comments/8', 'review comment');
eq(target('pull_request_review', { repository: repo, pull_request: { number: 4 }, review: { id: 7 } })?.method, 'PUT', 'review body is saved with PUT');
eq(target('push', { repository: repo }), null, 'other events touch nothing');

console.log(`test-scrub: OK · ${n} checks`);
